name: Neo
description: Generate a matrix depending on changed files
inputs:
  pattern:
    description: regex pattern with named groups to match against changed files
    required: true
  defaults:
    description: when set to true, if changed files don't match the pattern, recursively match all files in the repository.
    default: "false"
    required: false
  default-patterns:
    description: line separated list of UNIX-style glob patterns matched against the list of changed files. if match, switch to defaults mode.
    default: ""
    required: false
  ignore-deleted-files:
    description: whether to ignore the deleted files or not
    deprecationMessage: not used anymore
    default: "false"
    required: false
outputs:
  matrix:
    description: the output job matrix
    value: ${{ steps.neo.outputs.matrix }}
  matrix-length:
    description: the length of the matrix
    value: ${{ steps.neo.outputs.matrix-length }}
runs:
  using: composite
  steps:
    # required to compare the pattern on the files in the repo
    - if: inputs.defaults || inputs.default-patterns != ''
      uses: actions/checkout@v4

    - id: neo
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        DEFAULT_PATTERNS: ${{ inputs.default-patterns }}
      run: |
        ${{ github.action_path }}/neo/neo.py \
          --pattern "${{ inputs.pattern }}" \
          --defaults=${{inputs.defaults}} >> $GITHUB_OUTPUT

branding:
  icon: git-pull-request
  color: green
