name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  python-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./neo/tests.py TestChangedFiles -v

  python-integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./neo/tests.py IntegrationTest -v

  neo:
    name: Test action
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.neo.outputs.matrix }}
      matrix-length: ${{ steps.neo.outputs.matrix-length }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate matrix
        id: neo
        uses: ./
        env:
          NEO_LOG_LEVEL: DEBUG
        with:
          pattern: (?P<dir>[^/]+)/
          defaults: true
          default-patterns: |
            .github/**

  matrix-check:
    name: Check matrix
    runs-on: ubuntu-latest
    needs: [ neo ]
    strategy:
      matrix: ${{ fromJson(needs.neo.outputs.matrix ) }}
    steps:
      - name: Echo Matrix Directory
        run: echo ${{ matrix.dir }}

      - name: Echo Matrix Length
        run: echo ${{ needs.neo.outputs.matrix-length }}
